/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#29170c",
        "on-secondary-fixed": "#241a00",
        "surface-variant": "#eee1c9",
        "on-background": "#211b0c",
        "inverse-on-surface": "#fdefd7",
        "tertiary-fixed": "#e8e1da",
        "on-secondary": "#ffffff",
        "on-surface": "#211b0c",
        "surface-bright": "#fff8f1",
        "secondary-fixed-dim": "#e6c364",
        "on-secondary-fixed-variant": "#584400",
        "on-tertiary-fixed-variant": "#4a4641",
        "on-error-container": "#93000a",
        "tertiary-container": "#211e1a",
        "surface-dim": "#e5d9c1",
        "primary": "#0d0300",
        "on-secondary-container": "#785d00",
        "on-primary-container": "#9d806f",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fed977",
        "on-primary-fixed-variant": "#594234",
        "surface-container-high": "#f4e7cf",
        "surface": "#fff8f1",
        "primary-fixed-dim": "#e1c0ad",
        "inverse-surface": "#37301f",
        "on-tertiary-fixed": "#1e1b17",
        "surface-container-low": "#fff2db",
        "primary-fixed": "#fedcc8",
        "surface-container": "#faecd4",
        "secondary": "#755b00",
        "tertiary": "#060503",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-container": "#2c1a0e",
        "surface-container-highest": "#eee1c9",
        "secondary-fixed": "#ffe08f",
        "outline-variant": "#d3c4bc",
        "error-container": "#ffdad6",
        "inverse-primary": "#e1c0ad",
        "surface-tint": "#72594a",
        "on-surface-variant": "#4f453f",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "outline": "#81756e",
        "background": "#fff8f1",
        "tertiary-fixed-dim": "#ccc5bf",
        "on-tertiary-container": "#8a857f"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "body": ["Noto Serif", "serif"],
        "label": ["Work Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
